### ISSUE TITLE
A question related to the epipolar representation

### ISSUE THREAD

**Issue by phongnhhn92** [josh-tobin/egqn-datasets#1]
Hello,
I am reading your E-GQN paper and I am confusing how did you manage to compute fundamental matrix from context viewpoint and query viewpoint. From my point of view, you are trying to find the epipolar line corresponding to each point in the previous step hidden state representation. I am wondering if you are using SIFT to find pairs of matching points between views and caculate fundamental matrix.

**Comment by hyBlue** [comment]
I'm not the author but I think fundamental matrix was calculated using two camera poses, which are included in the dataset

**Comment by josh-tobin** [comment]
hyBlue is right, thanks!
